name: saber
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - contextily
  - geopandas
  - hydrostats
  - joblib
  - kneed
  - matplotlib
  - natsort
  - netCDF4
  - numba
  - numpy
  - pandas
  - pyarrow
  - requests
  - scipy
