name: saber
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - geopandas
  - pandas
  - numpy
  - numba
  - contextily
  - netCDF4
  - tslearn
  - pyarrow
  - kneed
  - tslearn
  - matplotlib
  - geoglows
  - requests
  - scipy
  - natsort
