site_name: SABER HBC
site_url: https://saber.hales.app
site_description: Documentation for the saber-hbc python package for hydrologic model bias correction
site_author: Riley C. Hales
copyright: 2022 Riley C. Hales
repo_url: https://github.com/rileyhales/saber-hbc/
theme: material
nav:
  - Home: index.md
  - User Guide:
      - Using SABER: user-guide/index.md
      - Required Datasets and Config File: user-guide/datasets.md
      - Working Directory and Generated Files: user-guide/working_directory.md
      - Assignments Table: user-guide/assignments_table.md
      - Visualization Tools: user-guide/visualization.md
      - Bias Correction: user-guide/bias_correction.md
      - Validation: user-guide/validation.md
  - Demonstration: demo/index.md
  - API Docs:
      - API Reference: api/index.md
      - saber.assign: api/assign.md
      - saber.bs: api/bs.md
      - saber.cluster: api/cluster.md
      - saber.gis: api/gis.md
  - Cite SABER: cite/index.md

plugins:
  - search
  - mkdocstrings
