# file paths to input data
workdir: ''

cluster_data: ''

drain_table: ''
gauge_table: ''
regulate_table: ''

drain_gis: ''
gauge_gis: ''

gauge_data: ''
hindcast_zarr: ''

# options for processing data
n_processes: 1
